#!/usr/bin/env python3
import os
import stat
from pathlib import Path
from subprocess import run

import requests

HOME = Path.home()
NVIM_URL = "https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage"
NVIM_INSTALL = f"{HOME}/.local/bin/nvim"
PACKAGES = f'{HOME}/.scripts/packages.txt'
PYPI_PACKAGES = f'{HOME}/.scripts/pypi_packages.txt'


def download_file(url, destination):
    print(f"Downloading {url} to {destination}")
    request = requests.get(url)
    with open(destination, "wb") as f:
        f.write(request.content)


def make_executable(file_name):
    os.chmod(file_name, os.stat(file_name).st_mode | stat.S_IEXEC)


def install_nvim_if_not_installed():
    if Path(NVIM_INSTALL).is_file():
        return
    print("Installing nvim")
    download_file(NVIM_URL, NVIM_INSTALL)
    make_executable(NVIM_INSTALL)


def install_packages():
    run(['xargs', '-a', PACKAGES, 'sudo', 'apt-get', 'install'], check=True)


def install_python_packages():
    run(['pip3', 'install', '-r', PYPI_PACKAGES], check=True)


def main():
    install_packages()
    install_nvim_if_not_installed()
    install_python_packages()


if __name__ == "__main__":
    main()
